name: Waka Readme (Spanish)

on:
  schedule:
    # Runs daily at midnight UTC (adjust as you want)
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-es:
    name: Actualizar README_es.md con métricas
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@v4
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: "es"
          SECTION_NAME: "waka_es"
          FILE_PATH: "README_es.md"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_DAYS_OF_WEEK:  "False"
          SHOW_LOC_CHART: "False"  
          SHOW_SHORT_INFO: "False"
